[[news]]
date = "2025-10"
content = "We have released LLMs4ALL, an extensive survey on LLMs for research and applications in academic disciplines."

[[news]]
date = "2025-05"
content = "NGQA is accepted to ACL 2025 main conference."

# [[news]]
# date = "2024-9"
# content = "Started my PhD journey at University of Notre Dame!"
